apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-tutorial-service-account
---
apiVersion: v1
kind: Secret
metadata:
  name: cicd-tutorial-service-account
  annotations:
    kubernetes.io/service-account.name: cicd-tutorial-service-account
type: kubernetes.io/service-account-token
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-tutorial-role
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
      - gateway.kyma-project.io
      - servicecatalog.k8s.io
      - networking.k8s.io
      - policy
      - services.cloud.sap.com
    resources:
      - deployments
      - replicasets
      - pods
      - jobs
      - configmaps
      - apirules
      - serviceinstances
      - servicebindings
      - services
      - secrets
      - networkpolicies
      - poddisruptionbudgets
      - servicebindings/status
      - serviceaccounts
    verbs:
      - create
      - update
      - patch
      - delete
      - get
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-tutorial-role-binding
subjects:
  - kind: ServiceAccount
    name: cicd-tutorial-service-account
    namespace: sidak
roleRef:
  kind: ClusterRole
  name: cicd-tutorial-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cicd-tutorial-config-map
data:
  out: "Congrats, you completed the cicd-tutorial successfully!"
