apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: participant-<id>
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: <your-host>
  service:
    name: bookshop-<id>-approuter
    port: 8080
  rules:
  - accessStrategies:
    - handler: allow
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /.*